http://canihazip.com/ have changed into https://canihazip.com/
markogresak/canihazip pull request #1
Opened 2018-01-26 08:55 UTC by LarsBuur

which makes the cli return 301 Moved Permanently. 
Have replaces http with https

2018-01-26 11:58 UTC, markogresak requested changes
Thanks for this fix! 👍 
Just one small change to keep the comment consistent with the code.

2018-01-26 11:58 UTC, markogresak commented on index.js
>   * TODO: Implement HTTPS. - has to be implemented on canihazip.com first.
This implements https, so the TODO comment is obsolete, please remove it.

2018-01-28 16:56 UTC, merged

2018-01-28 17:06 UTC, markogresak commented
I've merged this and I'll update the comment myself. 
There are some other fixes required to make the TravisCI build pass, this project is long overdue for some updates 😄

2018-01-29 07:26 UTC, LarsBuur commented
Hi - thanks. Good job.